version: "3.8"

services:
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      TZ: "Asia/Tokyo"
    env_file:
      - .env

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    ports:
        - 8888:80
    volumes:
        - pgadmin4_data:/var/lib/pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
        PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
    depends_on:
      - db
    env_file:
      - .env

  django:
    container_name: django
    build:
      context: .
      dockerfile: django/docker/Dockerfile
    ports:
      - 8000:8000
    expose:
      - 8000
    volumes:
      - ./django:/django
    command: sh -c "/django/docker/entrypoint.sh"
    depends_on:
      - db
    env_file:
      - .env

  react:
    container_name: react
    build:
      dockerfile: /react/docker/Dockerfile
    volumes:
      - ./react/node:/usr/src/app
    command: sh -c "cd /usr/src/app && yarn start"
    ports:
      - "3000:3000"
    depends_on:
      - django
    tty: true

volumes:
  db-store:
  postgres_data:
  pgadmin4_data: