# Generated by Django 4.1 on 2024-10-27 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='first_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
