# Generated by Django 4.1 on 2024-10-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_record_first_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_title_code', models.CharField(max_length=4)),
                ('label_title_name', models.TextField(max_length=15)),
            ],
        ),
    ]
