# Generated by Django 4.1 on 2024-10-28 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_labeltitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_detail_code', models.CharField(max_length=6)),
                ('label_detail_name', models.TextField(max_length=10)),
                ('label_title_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.labeltitle')),
            ],
        ),
    ]
