# Generated by Django 4.1 on 2024-12-21 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_labeldetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='label_title1',
            field=models.ForeignKey(blank=True, limit_choices_to={'label_title_code_id': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_title1', to='home.labeldetail'),
        ),
        migrations.AddField(
            model_name='record',
            name='label_title2',
            field=models.ForeignKey(blank=True, limit_choices_to={'label_title_code_id': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_title2', to='home.labeldetail'),
        ),
        migrations.AddField(
            model_name='record',
            name='label_title3',
            field=models.ForeignKey(blank=True, limit_choices_to={'label_title_code_id': 3}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_title3', to='home.labeldetail'),
        ),
        migrations.AddField(
            model_name='record',
            name='label_title4',
            field=models.ForeignKey(blank=True, limit_choices_to={'label_title_code_id': 4}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_title4', to='home.labeldetail'),
        ),
        migrations.AddField(
            model_name='record',
            name='label_title5',
            field=models.ForeignKey(blank=True, limit_choices_to={'label_title_code_id': 5}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_title5', to='home.labeldetail'),
        ),
        migrations.AddField(
            model_name='record',
            name='label_title6',
            field=models.ForeignKey(blank=True, limit_choices_to={'label_title_code_id': 6}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_title6', to='home.labeldetail'),
        ),
        migrations.AddField(
            model_name='record',
            name='label_title7',
            field=models.ForeignKey(blank=True, limit_choices_to={'label_title_code_id': 7}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_title7', to='home.labeldetail'),
        ),
        migrations.AddField(
            model_name='record',
            name='label_title8',
            field=models.ForeignKey(blank=True, limit_choices_to={'label_title_code_id': 8}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_title8', to='home.labeldetail'),
        ),
    ]
