# Generated by Django 4.1 on 2024-12-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_record_label_title1_record_label_title2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='ChooseLabel',  # 削除したいフィールド名
        ),
    ]
