# Generated by Django 4.1 on 2024-12-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_record_label_title1_record_label_title2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='home/picture/'),
        ),
    ]
